### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Khanmanan**
Its LOKING ugly try these https://rahuldkjain.github.io/gh-profile-readme-generator/

### CODE REVIEW

**Comment by Tanya575** [comment]
nice

**Comment by Khanmanan** [comment]
> nice tysm

Join my discord server 😅 check my profile

**Comment by Tanya575** [comment]
no sorry

**Comment by Khanmanan** [comment]
np 🥺 I want active members and mods that's why I asked u 🥺

**Comment by Tanya575** [comment]
You will get this someday

**Comment by Khanmanan** [comment]
Btw if u are dev check my profile 😂😂 https://cwkhan.xyz and automod-bot
deleted on GitHub I'll add new varsion soon

**Pull request closed without merging**
